### ISSUE TITLE
Code no longer recognizing UNKNOWNNAME manual tag

### ISSUE THREAD

**Issue by bmattan** [dalejn/cleanBib#23]
I cited a paper authored by the CDC. 

Before running the code, I updated the author name in the .bib file to: author = {UNKNOWNNAME, UNKNOWNNAME},

However, after running the gender API code, the classification of this paper was "male,male" with 100% probability. 
![image](https://user-images.githubusercontent.com/33105313/103034857-e4404d00-4533-11eb-97b6-1deeaf78c9b8.png)

**Comment by dalejn** [comment]
Hi Brad,

Thanks for using the code and for letting me know about this issue! I'll work on fixing it as soon as possible.

In the mean time, please feel free to launch the Binder from an old commit, which will let you use the prior version of the code. There, you can use cleanBib.csv to modify the calculated gender proportions. 

https://mybinder.org/v2/gh/dalejn/cleanBib/7ffe1823397a77c8c068b549c7b428c79379232e

**Comment by dalejn** [comment]
This looks like an issue with gender-api (see TAKE A TEST DRIVE section) https://gender-api.com/. 

If you use UKNOWNNAME**S**, it should work with the current main code
