### ISSUE TITLE
2 out of 32 publications not pulled from .bib to .csv file

### ISSUE THREAD

**Issue by bmattan** [dalejn/cleanBib#25]
Many thanks for creating and maintaining this excellent tool! 

I found that 2 out of 32 publications in a .bib file were not pulled into the .csv file that is generated in binder. So I had to manually enter those publications into the .csv file, which worked in the end. I'm not sure what went wrong, but I'll provide the output of the binder run in addition to the .bib and (edited) .csv file.

The two paper entries from the .bib file that I had to manually enter into the .csv were:

@article{caplar_quantitative_2017,
	title = {Quantitative evaluation of gender bias in astronomical publications from citation counts},
	volume = {1},
	issn = {2397-3366},
	url = {http://www.nature.com/articles/s41550-017-0141},
	doi = {10.1038/s41550-017-0141},
	language = {en},
	number = {6},
	urldate = {2020-12-23},
	journal = {Nature Astronomy},
	author = {Caplar, Neven and Tacchella, Sandro and Birrer, Simon},
	month = jun,
	year = {2017},
	pages = {0141},
	file = {Caplar et al. - 2017 - Quantitative evaluation of gender bias in astronom.pdf:/Users/brad/Zotero/storage/6EVPUKFZ/Caplar et al. - 2017 - Quantitative evaluation of gender bias in astronom.pdf:application/pdf}
}

@article{dworkin_extent_2020,
	title = {The extent and drivers of gender imbalance in neuroscience reference lists},
	volume = {23},
	doi = {10.1038/s41593-020-0658-y},
	language = {en},
	journal = {Nature Neuroscience},
	author = {Dworkin, Jordan D and Linn, Kristin A and Teich, Erin G and Zurn, Perry and Shinohara, Russell T and Bassett, Danielle S},
	year = {2020},
	pages = {918--926},
	file = {Dworkin et al. - The extent and drivers of gender imbalance in neur.pdf:/Users/brad/Zotero/storage/VTJYN994/Dworkin et al. - The extent and drivers of gender imbalance in neur.pdf:application/pdf}
}

[Archive.zip](https://github.com/dalejn/cleanBib/files/5883843/Archive.zip)

Cheers,

Brad

**Comment by dalejn** [comment]
Hi Brad,

Thanks for continuing to use this tool and for sending this along! We purposefully try to remove those citations. In the FAQ (https://github.com/dalejn/cleanBib#faq) section: "Should I include the diversity statement references in the proportion calculations? Please do not include the diversity statement references. The descriptive statistic of primary interest is of your citation practices." If these papers are part of your main text, this instruction might not apply because it is part of your paper's citations, rather than the diversity statement's citations.

**Comment by bmattan** [comment]
Thanks for the clarification, Dale. I was wondering about whether or not to
include the Citation Statement in the calculations. I decided to do that,
but in the future I will keep it just to papers cited in the main text.

Maybe adding a note that explains this in the Notebook/Binder instructions
may be one way of avoiding similar questions popping up from other users in
the future.

Cheers,

Brad

**Comment by dalejn** [comment]
Thanks! I'll add a line of instructions into the next code commit
