### ISSUE TITLE
Modifying diversity statement

### ISSUE THREAD

**Issue by mjcolebank** [dalejn/cleanBib#35]
Hello!

I'm interested in using this for our lab moving forward. I certainly appreciate the length and detail of the diversity statement, but I wanted to inquire whether we can make modifications to the text that is generated? For example, instead of including the original references in the pre-generated citations**, I was hoping to cite the BMES diversity letter found [here](https://link.springer.com/article/10.1007/s10439-021-02739-6) and this github account. Would that be feasible? 

**I feel as though leaving out the full list of citations may reduce the impact of the statement, but I'm in need of a more concise statement that can is directly related to the Biomedical Engineering community. I don't want to diminish the great work of this project!

**Comment by dalejn** [comment]
Hi it's great to hear that! You should certainly feel free to modify the template text and which references you include. We ourselves have gradually changed it over the years and many others have done so separately too, especially for journals with particularly austere text and citation limits. 

See for instance: 
https://arxiv.org/pdf/2112.14721.pdf
