### ISSUE TITLE
Parsing error in Block 3

### ISSUE THREAD

**Issue by dianaperez25** [dalejn/cleanBib#36]
I get this error when I try to run block 3: 

File contains parsing errors: 
	[line  2]: genderAPI_key <- '&key=####'

fileConn<-file("genderAPIkey.txt")
writeLines(c(genderAPI_key), fileConn)
close(fileConn)

Invalid statements: SyntaxError('invalid syntax', ('<string>', 19, 11, 'for(i in 1:nrow(names)){\n'))

**Comment by dalejn** [comment]
Hi, thanks for reaching out! I've edited your comment to remove the API key for privacy. I've just tried block 3 with your key and it looks like everything's working. Could it be that you're using a previously saved link or a bookmark to boot up the Binder? Note that we updated the link in the README, so please use that button to launch the Binder (that button should always contain a currently working link). [Link copied here](https://mybinder.org/v2/gh/dalejn/cleanBib/34b3a896b6fe0961b2dfc3ad22214cf45da48cca?urlpath=/tree/). Sorry about the mix-up! We changed this link a few months ago temporarily to fix a different issue and haven't gotten back to reverting it to the older, simpler one yet. Hopefully this resolves it--let me know if I can help more!
