### ISSUE TITLE
Binder Stuck Loading an Image

### ISSUE THREAD

**Issue by NRichbourg** [dalejn/cleanBib#52]
Hi dalejn,
I am trying to use your code, but when I open the Binder and look at the launch info, it looks like it repeatedly gets stuck trying to load a specific image:
Pulling image "2lmrrh8f.gra7.container-registry.ovh.net/mybinder-builds/r2d-g5b5b759dalejn-2dcleanbib-1020ef:c564df680919643f3dee7585bbd64d3762d70906"
Is it possible there is something wrong with that image and some way to fix it? Thank you.

Best,
Nate Richbourg, Ph.D.
nrichbourg@umass.edu

**Comment by dalejn** [comment]
Hi, thanks for checking out the tool! Could you try it again? It's hopefully a temporary issue with the myBinder server or possibly something to do with their migration to an updated Jupyter notebook. 

I just tried and it's loading successfully for me this morning:
https://mybinder.org/v2/gh/dalejn/cleanBib/HEAD?urlpath=/tree/

**Comment by NRichbourg** [comment]
Thanks, everything worked fine today!

Best,
Nate Richbourg

**Comment by dalejn** [comment]
Great, thanks!
