### ISSUE TITLE
Error message when running first step of cleanBib.ipynb

### ISSUE THREAD

**Issue by marinadoucerain** [dalejn/cleanBib#55]
Hello,

I'm trying to use cleanBib on the reference list of a manuscript in revision.

When running the first block of code in cleanBib.ipynb, I get the following error message:

> 2024-05-14 20:17:58.508042: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
> 2024-05-14 20:17:58.508119: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.

I have tried running it on my full reference list as well as on a very simple .bib file with only two references, same results. 

Any thoughts as to what might be the problem? I love the idea of cleanBib and am quite exciting about using it. Thank you!

**Comment by dalejn** [comment]
Hi, thanks for your message and for your interest in this! 

You can ignore those warnings and continue once that block of code finishes running. Later, there are some error messages that we purposefully built in to help modify the .bib file.

I just ran it on a test .bib and the rest of the code looks to be working as intended. Do the subsequent steps also return an error for you? Happy to help

**Comment by marinadoucerain** [comment]
Thanks!
