### ISSUE TITLE
Lack of automatic removal of unused citations from .aux file

### ISSUE THREAD

**Issue by jtaube** [dalejn/cleanBib#57]
Hello, thank you so much for creating this tool! 

It works great for me on a .bib file but now I'm trying to use it with both a .bib and .aux file where the .bib file contains some unused references. The unused refs are printing in Step 2, but based on the Changelog 2/17/2020 entry I thought these unused references would automatically be removed from the .bib file and not be included in cleanedBib.csv? Instead, I still see a list of all my .bib file entries as output of get_names(). Have I misunderstood and the unused references need to be removed manually? Or could you direct me to where in the code this removal is occurring?

Let me know if you need the files to reproduce the output. Thank you!

**Comment by dalejn** [comment]
Hi, thanks for trying out this tool and for carefully checking the expected outputs! Yes please do attach the files to reproduce this here or send to dalejn@gmail.com and I'll take a look

**Comment by dalejn** [comment]
Patched in https://github.com/dalejn/cleanBib/commit/24b937ab4eafb67d605093a26e4a0988ccde39a2
