### ISSUE TITLE
NameError:name 'cr' is not defined 

### ISSUE THREAD

**Issue by michigandrea** [dalejn/cleanBib#58]
Hello! I was hoping to use cleanBib to address the (lack of) citation diversity for a selection of publications, but I'm getting an error: 'NameError: name 'cr' is not defined'.

Screenshot below
![name_error](https://github.com/user-attachments/assets/cbf0aa02-4823-4214-b077-3d410b8cc530)

Thank you!

**Comment by dalejn** [comment]
Hi, thanks for trying this out! Can you double check whether the first step was run? There's a line in there that says:

```
cr = Crossref()
```

I just tried it out on a test .bib and it seems to be working. Feel free to let me know here if you run into any other issues.

**Comment by michigandrea** [comment]
Thank you for your quick reply!  I’m running this along with a colleague who is better at Python than I am. She says she printed out the cr object before the error occurs and something is returned, so she is pretty sure cr is being created.

Can you advise whether we should use 'checkingPublishedArticle = True' or False if we are finding the citations in Web of Science, then importing into Zotero before outputting from there as a .bib file?

Thank you!

Andrea

Andrea H. Denton, MILS
Research & Data Services Manager
UVA Claude Moore Health Sciences Library
***@***.******@***.***>

**Comment by dalejn** [comment]
Got it--you can keep checkingPublishedArticle=False if you've already put together a .bib file. If you attach the .bib file here or send it to me via email (dalejn@gmail.com), I can help you troubleshoot this more directly.
